# Generated by Django 5.0.4 on 2024-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedtitles',
            name='score',
            field=models.IntegerField(),
        ),
    ]
